### ISSUE TITLE
Update B-12 document for cross-references and bibliography

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-iho#1]
I've converted the B-12 document but these are still missing:

* cross-references within document
* references / bibliography
* links from content to terminology

This issue is to complete them.

**Comment by ronaldtse** [comment]
@manuel489 the Word version is now provided. It might help...

**Comment by ronaldtse** [comment]
Ping @manuel489.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, I was attending other issues (like https://github.com/metanorma/mn-samples-iho/issues/3). But I'm going to prioritize this one.

**Comment by ronaldtse** [comment]
No problem, I just wanted to confirm that you're aware of this one. Either order is fine. Thanks!

**Comment by manuelfuenmayor** [comment]
PR added in https://github.com/metanorma/mn-samples-iho/pull/6

**Comment by ronaldtse** [comment]
Closed by #6. Thanks!
