### ISSUE TITLE
Convert S-5 Guidelines

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-iho#10]
[S-5_S-8-Guidelines-Ed_2.1.0.pdf](https://github.com/metanorma/mn-samples-iho/files/4416434/S-5_S-8-Guidelines-Ed_2.1.0.pdf)

**Comment by manuelfuenmayor** [comment]
PR added in https://github.com/metanorma/mn-samples-iho/pull/26

**Comment by manuelfuenmayor** [comment]
PR approved and merged. Closing.
