### ISSUE TITLE
Complete S-63 conversion

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-iho#2]
I have converted the first 2 sections of S-63, but the bulk remains.

To facilitate this task I have made screenshots of all images in the document.

This issue is to complete the conversion of this document.

@anermina could you help with this? Thanks!

**Comment by anermina** [comment]
Sure! 
There are several more docs and PDFs besides from S-63_2020_Ed1.2.1_EN_Draft_Clean.pdf in https://github.com/metanorma/mn-samples-iho/tree/master/reference-docs/s-63 . Should I convert the rest of them as well?

**Comment by ronaldtse** [comment]
@anermina we can ignore those for now. Some of those are too long to do at this stage. Thanks!

**Comment by ronaldtse** [comment]
@anermina the Word version is now provided. Hope this helps!

**Comment by anermina** [comment]
@ronaldtse perfect, thanks!

**Comment by ronaldtse** [comment]
Done in #4 .
