### ISSUE TITLE
Check all IHO samples

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-iho#30]
metanorma-iho is now in alpha stage, we need to check the sample documents to ensure the output (in text, not design) is correct.

@metanorma/editors Can you please help check every document to ensure the output is correct (esp. metadata like document codes, dates etc)? Thanks!

* [x] b12
* [x] c17
* [x] s102
* [x] s44
* [x] s5-guidelines
* [x] s5a
* [x] s5b
* [x] s63

**Comment by anermina** [comment]
Since B12 document review is quite long, I opened the issue #35 which lists all of them. Corrections in .adoc are made in #34 .

**Comment by anermina** [comment]
Changes for IHO C17 are made in #36 .

**Comment by anermina** [comment]
Changes for IHO S102 are made in #37 .

**Comment by anermina** [comment]
Changes for IHO S44 are made in #38 and #39.

**Comment by anermina** [comment]
Changes for:
- IHO S5-guidelines are made in #40,
- IHO S5a are made in #41.

I was quite struggling with document metadata (especially workgroup, which is a mandatory attribute), so I would like to ask @manuel489 to double-check the metadata for IHO documents when possible. Thanks in advance!

**Comment by anermina** [comment]
Changes for IHO S63 are made in #43.

Note: IHO references can currently not be auto-fetched. When auto-fetching option is added for IHO, bibliography in this .adoc should be corrected.

**Comment by manuelfuenmayor** [comment]
IHO C17 double-checked. Two issues described in https://github.com/metanorma/mn-samples-iho/issues/44

**Comment by anermina** [comment]
Thanks @manuel489 ! I thought you were going to double-check only document attributes here :)

**Comment by manuelfuenmayor** [comment]
> Thanks @manuel489 ! I thought you were going to double-check only document attributes here :)

Well, yeah. I just considered prudent to take a quick look at the content as well 👍

**Comment by manuelfuenmayor** [comment]
S-44 and S63 are double-checked. I have no further comments to make on those.
And, since S-5-guidelines, S5a and S5b are already merged, I believe there is no need to re-check them.

**Comment by ronaldtse** [comment]
Awesome thanks! Closing.
