### ISSUE TITLE
IHO B12 document review

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-iho#35]
Differences in content noticed by comparison of the original and generated IHO B12 document are written below.

- List of Figures and List of Tables are missing.

Original:
![image](https://user-images.githubusercontent.com/55683568/82150541-103a7800-9859-11ea-8579-54995fb53e82.png)
![image](https://user-images.githubusercontent.com/55683568/82150567-16305900-9859-11ea-8e92-91005d87d55a.png)

- IHO B12 uses chapters and sections instead of clauses. In generated document, cross-references are placed where "Chapter" + its number should be written, while they are placed on chapter titles in generated document. I believe generated document is fine, due to automatic naming of cross-references depending on chapters/clauses, so I didn't make any change in .adoc. In case change is needed, please let me know.

Original (chapters):
![image](https://user-images.githubusercontent.com/55683568/82151305-3c56f880-985b-11ea-8901-c5f6bf213b12.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82151326-4c6ed800-985b-11ea-85a7-7d7acba4016a.png)

Original (sections):
![image](https://user-images.githubusercontent.com/55683568/82151945-93aa9800-985e-11ea-9aec-36e03909cd1c.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82151955-9ad1a600-985e-11ea-93f4-eeb3acaf20db.png)

- Following images show that chapter name is written without quotes in the original, unlike in generated document. However, since they are all written with quotes in the preface, I didn't make a change in .adoc, because this might be an inconsistency issue in IHO document itself. If change is needed, please let me know.

Original:
![image](https://user-images.githubusercontent.com/55683568/82151644-c2277380-985c-11ea-806f-c06b31829640.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82151657-cce20880-985c-11ea-8f8f-d238f0658ae7.png)

- Original document doesn't have a heading in Table 3. I didn't make a change in .adoc in this case either, because I believe heading should be present. If not, please let me know.

Original:
![image](https://user-images.githubusercontent.com/55683568/82151842-eafc3880-985d-11ea-8f35-bb9d658164e4.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82151847-f0f21980-985d-11ea-8e6c-96c8f7b651cd.png)

- Other changes in source .adoc are made in #34 (added cross-references, fixed figures and fixed general markup issues).

At first I thought copyright was written by our team (and is incomplete due to the alpha phase of IHO conversion), but then I realized by comparing copyrights from other documents with the ones provided in original and generated B12 that it is "incomplete" in the original documents as well. 
Below are the copyright differences which were noticed in B12, but in case this copyright was provided by IHO and should remain as-is, please ignore these comments.

- Copyright: 2nd paragraph. "IHO Secretatiat" in the original vs. "IHO" in generated document.

Original:
![image](https://user-images.githubusercontent.com/55683568/82149006-019e9180-9856-11ea-8636-dbaf8a3977b8.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82148998-f8adc000-9855-11ea-91ac-e9a08237f9a9.png)

- Copyright: first two paragraphs. Some commas are missing in generated document. Missing ones are yellow highlighted in the original document (image below).

Original:
![image](https://user-images.githubusercontent.com/55683568/82152455-893dcd80-9861-11ea-9ea6-30b63562d97e.png)

- Copyright: 4th and 5th paragraph. "IHO Secretariat" in original vs. "International Hydrographic Organization (IHO) Secretariat" in generated document (yellow highlighted).

Since IHO conversion is in alpha stage, I just underlined (red) terms in generated document which should be replaced with specific names. However, I believe "source version of [name] in" should currently be written as "source version of IHO [document/publication] [name] in" (blue underlined in the original document). Moreover, it seems "translation of IHO [document/publication] [name]" should be written as "translation of IHO [nameFull]" (blue and black underlined in the original document). `nameFull` would be a full name of publication/document in this case.

Original:
![image](https://user-images.githubusercontent.com/55683568/82149840-9b1a7300-9857-11ea-8246-521d22a8ab3f.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82153875-7b407a80-986a-11ea-837c-7a341b8df42f.png)

- Copyright: last paragraph. "IHO Secretariat" in original vs. "IHO" in generated document.

Original:
![image](https://user-images.githubusercontent.com/55683568/82150309-8b4f5e80-9858-11ea-8643-087718c507cc.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/82150313-93a79980-9858-11ea-9803-3bfcb441a167.png)

**Comment by manuelfuenmayor** [comment]
Thanks @anermina, I have double-checked this document and no additional comment to make. Just minor markup corrections that I made on the way.

>Original document doesn't have a heading in Table 3. I didn't make a change in .adoc in this case either, because I believe heading should be present. If not, please let me know.

Yes, I decided to add the heading because I thought it should be present by comparison with the previous table.

**Comment by opoudjis** [comment]
> "1". List of Figures and List of Tables are missing.

Lists of figures and tables are missing from all other sample documents. I refuse to implement them without explicit instruction from IHO.

> "2". IHO B12 uses chapters and sections instead of clauses

Confirmed in S-63, implementing

**Comment by opoudjis** [comment]
Copyright statement is indeed very inconsistent in the source documents; the generic version of the boilerplate has been used in one document. Without any formal advice from IHO, I will not change it. @ronaldtse, it would be useful for you to forward Nermina's analysis to IHO.

**Comment by ronaldtse** [comment]
IHO's new Technical Director isn't free yet to look at this... We'll have to keep this open.

**Comment by opoudjis** [comment]
Delegating to new ticket.
