### ISSUE TITLE
Convert IHO references to auto-fetch using relaton-iho

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-iho#54]
Once https://github.com/relaton/relaton-data-iho/issues/11 is done, convert all document bibliographies to use auto-fetch of IHO documents.

**Comment by manuelfuenmayor** [comment]
Got it.

**Comment by manuelfuenmayor** [comment]
Compilation failure when IHO references are slightly misspelled for auto-fetch: https://github.com/relaton/relaton-iho/issues/7

**Comment by manuelfuenmayor** [comment]
PR added in https://github.com/metanorma/mn-samples-iho/pull/55

**Comment by manuelfuenmayor** [comment]
Task merged. Closing.
