### ISSUE TITLE
Fix invalid bibdata

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn-samples-iho#68]
https://github.com/metanorma/mn-samples-iho/runs/2047701948?check_suite_focus=true

Per https://github.com/relaton/relaton-iho/issues/11#issuecomment-792271358 we have an invalid document because 

> ... Elements `committee`, `workgroup`, and `commission` should have an `abbreviation`.

Ping @metanorma/editors

**Comment by anermina** [comment]
`workgroup` attribute was missing in M-1. Fixed in https://github.com/metanorma/mn-samples-iho/pull/69. Closing.
