### ISSUE TITLE
Convert C-17 document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-iho#7]
[C-17_Ed2.0.0_EN.pdf](https://github.com/metanorma/mn-samples-iho/files/4416420/C-17_Ed2.0.0_EN.pdf)

**Comment by ronaldtse** [comment]
This is now actionable.
[C-17_Ed2.0.0.docx](https://github.com/metanorma/mn-samples-iho/files/4423228/C-17_Ed2.0.0.docx)

**Comment by anermina** [comment]
Converted in #18.
