### ISSUE TITLE
Update S-102 to 2.1.0

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-iho#76]
[s-102.pdf](https://github.com/metanorma/mn-samples-iho/files/9867494/s-102.pdf)

IHO Secretariat, Yong (@iho-ohi), will send us the Word version for conversion.

**Comment by ronaldtse** [comment]
Thank you @iho-ohi for sharing the document!

[S-102_Ed 2.1.0_Final.docx](https://github.com/metanorma/mn-samples-iho/files/9870910/S-102_Ed.2.1.0_Final.docx)

@metanorma/editors this is now ready for action. The 2.0.0 Word document is found under reference-docs.

**Comment by anermina** [comment]
Done in #77 .
